### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by sargent-coding** [ideoxan/ideoxan#158] opened 2021-01-14 12:21 UTC
![image](https://user-images.githubusercontent.com/65425469/104590258-11ff4a00-5639-11eb-921f-3c4cd116cf45.png)

**Comment by Skyclo** [comment] 2021-01-14 13:43
@sargent-coding Is this on https://ideoxan.com?

**Comment by Skyclo** [comment] 2021-01-14 17:43
Okay issue confirmed. Investigating the issue.

**Comment by sargent-coding** [comment] 2021-01-14 18:05
![image](https://user-images.githubusercontent.com/65425469/104630742-2d824900-5669-11eb-9628-3bbe12ca88cb.png)

**Comment by Skyclo** [comment] 2021-01-14 18:12
So apparently, the server synced the newest ideoxan/curriculum-tutorial module which resulted in the error. I could "roll back" the update but this would be pointless because the server automatically `git pull`s all sub-modules on startup. For now, I have replaced the website with the old "Coming soon" page. Until the website redesign is done, the website will stay this way. 

In other news, its now safe to assume that the server/website `master` branch no longer works. This should be fixed soon.

**Comment by micahlt** [comment] 2021-01-14 18:16
@Skyclo Can you not target the repository at a specific commit/release version?

**Comment by Skyclo** [comment] 2021-01-14 18:19
> 
> 
> @Skyclo Can you not target the repository at a specific commit/release version?

See I could by checking out that version of the course, but the problem is that the server runs a script when it restarts that updates the submodules. I think that leaving this in is the best idea because it will be used heavily in production later on. Plus, I really should have the coming soon page online rather than the old website that no longer serves a purpose.

**Closed** 2021-01-21 18:01 UTC
Labels: Other, Server, Website, bug (critical)
